services:
  api:
    # build:
    #   context: ./backend
    image: nikiakbar/vuvur:api
    pull_policy: always
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      # core requirements
      - /srv/vuvur/data:/app/data

      - /mnt/z/Locals/system/outputs/txt2img-images:/mnt/gallery/images
      # - ./media/videos:/mnt/gallery/videos
      - /mnt/z/Locals/system/liked:/mnt/gallery/liked
    restart: unless-stopped

  portal:
    # build:
    #   context: ./frontend
    image: nikiakbar/vuvur:portal
    pull_policy: always
    ports:
      - "${PORTAL_PORT:-8080}:80"
    depends_on:
      - api
    restart: unless-stopped
    environment:
      - VITE_RANDOM_PRELOAD_COUNT=3
      - VITE_RANDOM_HISTORY_SIZE=5