services:
  # Backend API Service
  api:
    build:
      context: ./backend
    ports:
      # Maps the host port (from .env, defaults to 5000) to the container's port 5000
      - "${API_PORT:-5000}:5000"
    volumes:
      # Persist media files on your host machine
      - ./backend/media:/app/media
    restart: unless-stopped

  # Frontend Portal Service
  portal:
    build:
      context: ./frontend
    ports:
      # Maps the host port (from .env, defaults to 8080) to the container's port 80 (Nginx)
      - "${PORTAL_PORT:-8080}:80"
    depends_on:
      - api # Ensures the backend starts before the frontend
    restart: unless-stopped