services:
  api:
    # build:
    #   context: ./backend
    image: nikiakbar/vuvur:api
    pull_policy: always
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      # Persist the generated previews
      - /srv/vuvur/cache_preview:/mnt/cache_preview
      # Persist the generated thumbnails
      - /srv/vuvur/cache_thumb:/mnt/cache_thumb
      
      # Persist media files on your host machine
      - /mnt/z/Locals/system/outputs/txt2img-images:/mnt/all
      # - /mnt/z/Locals/system/outputs-f15/txt2img-images/2025-04:/app/media/all
      - /mnt/z/Locals/system/outputs-f15/txt2img-images/liked:/mnt/liked
    restart: unless-stopped

  portal:
    # build:
    #   context: ./frontend
    image: nikiakbar/vuvur:portal
    pull_policy: always
    ports:
      - "${PORTAL_PORT:-8080}:80"
    depends_on:
      - api
    restart: unless-stopped